[theme]
base = "light"

primaryColor = "#6366F1"                 # Indigo-500
backgroundColor = "#FFFFFF"              # White
secondaryBackgroundColor = "#F6F7FB"     # Subtle panel
textColor = "#0F172A"                    # Slate-900
linkColor = "#2563EB"                    # Blue-600
linkUnderline = false
codeBackgroundColor = "#F3F4F6"          # Gray-100

font = "Inter, system-ui, -apple-system, Segoe UI, Roboto, sans-serif"
baseFontSize = 16
baseFontWeight = 400
headingFont = "Inter, ui-sans-serif, system-ui, sans-serif"
headingFontSizes = ["2.25rem","1.875rem","1.5rem","1.25rem","1.125rem","1rem"]
headingFontWeights = [700,600,600,600,600,600]

codeFont = "JetBrains Mono, ui-monospace, SFMono-Regular, Menlo, monospace"
codeFontSize = "0.9rem"
codeFontWeight = 450

baseRadius = "0.75rem"
buttonRadius = "0.75rem"
borderColor = "#E5E7EB"                  # Gray-200
dataframeBorderColor = "#E5E7EB"
dataframeHeaderBackgroundColor = "#EEF2FF"  # Indigo-50

showWidgetBorder = false
showSidebarBorder = false

chartCategoricalColors = [
  "#6366F1","#22C55E","#F59E0B","#EF4444",
  "#06B6D4","#A855F7","#84CC16","#E11D48",
  "#0EA5E9","#F97316"
]

chartSequentialColors = [
  "#EEF2FF","#E0E7FF","#C7D2FE","#A5B4FC","#818CF8",
  "#6366F1","#4F46E5","#4338CA","#3730A3","#312E81"
]
